# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cert.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import public_key_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cert.proto',
  package='',
  serialized_pb=_b('\n\ncert.proto\x1a\x10public_key.proto\"m\n\x04\x43\x65rt\x12\x1e\n\x07version\x18\x01 \x02(\x0e\x32\r.Cert.Version\x12#\n\npublic_key\x18\x02 \x01(\x0b\x32\r.RSAPublicKeyH\x00\"\x15\n\x07Version\x12\n\n\x06_0_0_1\x10\x00\x42\t\n\x07KeyType')
  ,
  dependencies=[public_key_pb2.DESCRIPTOR, ])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CERT_VERSION = _descriptor.EnumDescriptor(
  name='Version',
  full_name='Cert.Version',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_0_0_1', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=109,
  serialized_end=130,
)
_sym_db.RegisterEnumDescriptor(_CERT_VERSION)


_CERT = _descriptor.Descriptor(
  name='Cert',
  full_name='Cert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Cert.version', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='Cert.public_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CERT_VERSION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='KeyType', full_name='Cert.KeyType',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=32,
  serialized_end=141,
)

_CERT.fields_by_name['version'].enum_type = _CERT_VERSION
_CERT.fields_by_name['public_key'].message_type = public_key_pb2._RSAPUBLICKEY
_CERT_VERSION.containing_type = _CERT
_CERT.oneofs_by_name['KeyType'].fields.append(
  _CERT.fields_by_name['public_key'])
_CERT.fields_by_name['public_key'].containing_oneof = _CERT.oneofs_by_name['KeyType']
DESCRIPTOR.message_types_by_name['Cert'] = _CERT

Cert = _reflection.GeneratedProtocolMessageType('Cert', (_message.Message,), dict(
  DESCRIPTOR = _CERT,
  __module__ = 'cert_pb2'
  # @@protoc_insertion_point(class_scope:Cert)
  ))
_sym_db.RegisterMessage(Cert)


# @@protoc_insertion_point(module_scope)
