# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public_key.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='public_key.proto',
  package='',
  serialized_pb=_b('\n\x10public_key.proto\"z\n\x0cRSAPublicKey\x12&\n\x07version\x18\x01 \x02(\x0e\x32\x15.RSAPublicKey.Version\x12\x17\n\x0fpublic_key_hash\x18\x02 \x02(\x0c\x12\x12\n\npublic_key\x18\x03 \x02(\x0c\"\x15\n\x07Version\x12\n\n\x06_0_0_1\x10\x00\"y\n\x0cRSASignature\x12&\n\x07version\x18\x01 \x02(\x0e\x32\x15.RSASignature.Version\x12\x17\n\x0fpublic_key_hash\x18\x02 \x02(\x0c\x12\x11\n\tsignature\x18\x03 \x02(\x0c\"\x15\n\x07Version\x12\n\n\x06_0_0_1\x10\x00')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RSAPUBLICKEY_VERSION = _descriptor.EnumDescriptor(
  name='Version',
  full_name='RSAPublicKey.Version',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_0_0_1', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=121,
  serialized_end=142,
)
_sym_db.RegisterEnumDescriptor(_RSAPUBLICKEY_VERSION)

_RSASIGNATURE_VERSION = _descriptor.EnumDescriptor(
  name='Version',
  full_name='RSASignature.Version',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_0_0_1', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=121,
  serialized_end=142,
)
_sym_db.RegisterEnumDescriptor(_RSASIGNATURE_VERSION)


_RSAPUBLICKEY = _descriptor.Descriptor(
  name='RSAPublicKey',
  full_name='RSAPublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='RSAPublicKey.version', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public_key_hash', full_name='RSAPublicKey.public_key_hash', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='RSAPublicKey.public_key', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RSAPUBLICKEY_VERSION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=142,
)


_RSASIGNATURE = _descriptor.Descriptor(
  name='RSASignature',
  full_name='RSASignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='RSASignature.version', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public_key_hash', full_name='RSASignature.public_key_hash', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='RSASignature.signature', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RSASIGNATURE_VERSION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=265,
)

_RSAPUBLICKEY.fields_by_name['version'].enum_type = _RSAPUBLICKEY_VERSION
_RSAPUBLICKEY_VERSION.containing_type = _RSAPUBLICKEY
_RSASIGNATURE.fields_by_name['version'].enum_type = _RSASIGNATURE_VERSION
_RSASIGNATURE_VERSION.containing_type = _RSASIGNATURE
DESCRIPTOR.message_types_by_name['RSAPublicKey'] = _RSAPUBLICKEY
DESCRIPTOR.message_types_by_name['RSASignature'] = _RSASIGNATURE

RSAPublicKey = _reflection.GeneratedProtocolMessageType('RSAPublicKey', (_message.Message,), dict(
  DESCRIPTOR = _RSAPUBLICKEY,
  __module__ = 'public_key_pb2'
  # @@protoc_insertion_point(class_scope:RSAPublicKey)
  ))
_sym_db.RegisterMessage(RSAPublicKey)

RSASignature = _reflection.GeneratedProtocolMessageType('RSASignature', (_message.Message,), dict(
  DESCRIPTOR = _RSASIGNATURE,
  __module__ = 'public_key_pb2'
  # @@protoc_insertion_point(class_scope:RSASignature)
  ))
_sym_db.RegisterMessage(RSASignature)


# @@protoc_insertion_point(module_scope)
