# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signature.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import public_key_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='signature.proto',
  package='',
  serialized_pb=_b('\n\x0fsignature.proto\x1a\x10public_key.proto\"|\n\tSignature\x12#\n\x07version\x18\x01 \x02(\x0e\x32\x12.Signature.Version\x12\"\n\tsignature\x18\x02 \x01(\x0b\x32\r.RSASignatureH\x00\"\x15\n\x07Version\x12\n\n\x06_0_0_1\x10\x00\x42\x0f\n\rSignatureType')
  ,
  dependencies=[public_key_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SIGNATURE_VERSION = _descriptor.EnumDescriptor(
  name='Version',
  full_name='Signature.Version',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_0_0_1', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=123,
  serialized_end=144,
)
_sym_db.RegisterEnumDescriptor(_SIGNATURE_VERSION)


_SIGNATURE = _descriptor.Descriptor(
  name='Signature',
  full_name='Signature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Signature.version', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Signature.signature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SIGNATURE_VERSION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='SignatureType', full_name='Signature.SignatureType',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=37,
  serialized_end=161,
)

_SIGNATURE.fields_by_name['version'].enum_type = _SIGNATURE_VERSION
_SIGNATURE.fields_by_name['signature'].message_type = public_key_pb2._RSASIGNATURE
_SIGNATURE_VERSION.containing_type = _SIGNATURE
_SIGNATURE.oneofs_by_name['SignatureType'].fields.append(
  _SIGNATURE.fields_by_name['signature'])
_SIGNATURE.fields_by_name['signature'].containing_oneof = _SIGNATURE.oneofs_by_name['SignatureType']
DESCRIPTOR.message_types_by_name['Signature'] = _SIGNATURE

Signature = _reflection.GeneratedProtocolMessageType('Signature', (_message.Message,), dict(
  DESCRIPTOR = _SIGNATURE,
  __module__ = 'signature_pb2'
  # @@protoc_insertion_point(class_scope:Signature)
  ))
_sym_db.RegisterMessage(Signature)


# @@protoc_insertion_point(module_scope)
